import { Button } from 'antd'
import Head from 'next/head'
import MainLayout from 'layouts'


export default function Home() {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button
        type="primary"
      >
          Button
      </Button>
    </MainLayout>
  )
}
