import { Button, Card, Col, Row, Space } from 'antd'
import Head from 'next/head'
import Highcharts from 'highcharts'
import HighchartsReact from 'highcharts-react-official'

import MainLayout from 'layouts'
import Container from 'components/container'


export default function Home() 
{

    const chartOptions = {
        chart: {
            height: 500,
        },
        title: {
            text: 'Pool Hashrate'
        },
        xAxis: {
            gridLineWidth: 1,
            categories: ['10.12', '10.12', '10.12', '10.12', '10.12', '10.12', '10.12'],
        },
        series: [{
            data: [12, 223, 234, 1234,232, 234,123,343]
        }]

    }

    const chartOptions2 = {
        chart: {
            height: 215,
        },
        title: {
            text: 'Network Difficulty'
        },
        series: [{
            data: [12, 223, 234, 123,2343 ]
        }]
    }

    const chartOptions3 = {
        chart: {
            height: 215,
        },
        title: {
            text: 'Pool Workers'
        },
        series: [{
            data: [12, 223, 234, 123,2343 ]
        }]
    }

    const chartOption4 = {
        accessibility: { enabled: false },
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie',
            height: 215
        },
        title: {
            text: ''
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },

        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    connectorColor: 'silver'
                }
            }
        },
        series: [
            {
                name: 'Share',
                type: 'pie',
                data: [
                    { name: 'Chrome', y: 73.24, color: '#130685' },
                    { name: 'Edge', y: 12.93, color: '#cc03b1' },
                    { name: 'Firefox', y: 4.73, color: '#8b8d00' },
                    { name: 'Safari', y: 2.50, color: '#027c12' },
                    { name: 'Internet Explorer', y: 1.65, color: '#160bac' },
                    { name: 'Other', y: 4.93, color: '#eb3e3e' }
                ]
            }
        ]
    }



    return (
        <MainLayout>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container>
                <Row
                    gutter={[24, 24]}
                >
                    <Col
                        span={12}
                    >
                        <Card>
                            <HighchartsReact
                                highcharts={Highcharts}
                                options={chartOptions}
                            />
                        </Card>
                    </Col>
                    <Col
                        span={6}
                    >
                        <Space
                            direction="vertical"
                            size={24}
                        >
                            <Card>
                                <HighchartsReact
                                    highcharts={Highcharts}
                                    options={chartOptions2}
                                />
                            </Card>
                            <Card>
                                <HighchartsReact
                                    highcharts={Highcharts}
                                    options={chartOptions3}
                                />
                            </Card>
                        </Space>
                    </Col>
                    <Col
                        span={6}
                    >
                        <Space
                            direction="vertical"
                            size={24}
                        >
                            <Card>
                                <HighchartsReact
                                    highcharts={Highcharts}
                                    options={chartOption4}
                                />
                            </Card>
                            <Card>
                                <HighchartsReact
                                    highcharts={Highcharts}
                                    options={chartOptions3}
                                />
                            </Card>
                        </Space>
                    </Col>
                </Row>
            </Container>
        </MainLayout>
    )
}
